import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>

      <div>
        <h1> Bienvenue sur code.io  </h1>
        <p>Le blog comunautaire des afacinados de devellopement web</p>
      </div>

      <div style={{ 'marginTop': '40px' }}>
        <Link href="/blog">
          <a className={styles.card}> Visiter le blog </a>
        </Link>
        <Link href="/liste">
          <a className={styles.card}> Decouvre la liste de menbres </a>
        </Link>
      </div>


    </div>
  )
}
